export const words = [
  "time", "man", "school", "go", "down", "tell", "eye", "home", "form",
  "high", "which", "number", "feel", "play", "good", "child", "work",
  "fact", "group", "before", "each", "never", "people", "hard", "think",
  "day", "way", "life", "line", "mean", "hold", "state", "lead", "next",
  "old", "hope", "fast", "true", "write", "read", "move", "stand", "shift",
  "flow", "rate", "task", "fun", "easy", "skill", "start", "stop", "run",
  "load", "save", "open", "close", "send", "post", "get", "put", "call",
  "page", "view", "link", "list", "item", "check", "valid", "error", "warn",
  "slow", "bug", "fix", "dev", "main",
  "house", "tree", "river", "water", "light", "dark", "sky", "cloud",
  "rain", "wind", "fire", "earth", "stone", "mountain", "hill", "field",
  "road", "street", "car", "bus", "train", "plane", "city", "town", "village",
  "dog", "cat", "bird", "horse", "fish", "cow", "bear", "apple", "mango",
  "banana", "grape", "milk", "bread", "rice", "sugar", "salt", "sweet",
  "hot", "cold", "warm", "dry", "wet", "big", "small", "short", "long",
  "tall", "young", "old", "man", "woman", "boy", "girl", "friend", "family",
  "father", "mother", "brother", "sister", "uncle", "aunt", "cousin", "baby",
  "chair", "table", "room", "door", "window", "bed", "pen", "book", "paper",
  "phone", "watch", "bag", "hat", "shoe", "shirt", "dress", "color", "red",
  "blue", "green", "black", "white", "yellow", "happy", "sad", "angry",
  "love", "hate", "smile", "laugh", "cry", "run", "walk", "sit", "stand",
  "sleep", "wake", "talk", "listen", "see", "hear", "think", "know", "say",
  "do", "make", "take", "give", "come", "leave", "live", "die", "eat", "drink",
  "buy", "sell", "pay", "find", "lose", "start", "stop", "win", "fail",
  "plant", "sand", "beach", "lake", "sea", "boat", "king", "queen", "prince",
  "girl", "boy", "uncle", "aunt", "teacher", "student", "story", "book",
  "movie", "song", "music", "dance", "art", "paint", "draw", "game", "match",
  "team", "ball", "goal", "score", "point", "walk", "run", "jump", "laugh",
  "cry", "shout", "whisper", "quiet", "loud", "bright", "dark", "clean",
  "dirty", "soft", "hard", "early", "late", "true", "false", "kind", "mean",
  "rich", "poor", "young", "old", "fast", "slow", "strong", "weak", "thin",
  "fat", "tall", "short", "near", "far", "new", "used", "open", "shut",
  "top", "bottom", "first", "last", "again", "always", "never", "maybe",
  "sure", "often", "sometimes", "inside", "outside", "under", "over"
];
